# Generated by Django 4.0.5 on 2022-10-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=0)),
                ('solutions', models.IntegerField(default=0)),
                ('image', models.ImageField(default='profile_pics/default.jpeg', upload_to='profile_pics/')),
                ('classes', models.ManyToManyField(blank=True, default=None, related_name='profiles', to='classroom.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
