# Generated by Django 4.0.5 on 2022-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, default=None, max_length=1000),
        ),
    ]
