# Generated by Django 4.0.5 on 2022-06-24 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_projectvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ProjectComment',
        ),
        migrations.RenameModel(
            old_name='CommentNotification',
            new_name='ProjectCommentNotification',
        ),
    ]
