# Generated by Django 4.0.5 on 2022-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
