# Generated by Django 4.0.5 on 2022-10-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
    ]
