# Generated by Django 4.0.5 on 2022-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projectphoto_image_alter_projectvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='classroom',
            field=models.CharField(choices=[('a', 'b'), ('b', 'b')], default=None, max_length=100),
        ),
    ]
