# Generated by Django 4.0.5 on 2022-07-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_project_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
