# Generated by Django 4.0.5 on 2022-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_image_alter_projectphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blurb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
