# Generated by Django 4.0.5 on 2022-07-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_project_blurb_alter_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('blurb', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_link', models.URLField(blank=True, default=None, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default=None, max_length=1000)),
                ('temp_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_project_videos', to='users.tempproject')),
            ],
        ),
    ]
