# Generated by Django 4.0.5 on 2022-07-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tempproject_tempprojectvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='project_pics')),
                ('temp_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_photos', to='users.tempproject')),
            ],
        ),
    ]
