# Generated by Django 4.0.5 on 2022-07-22 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_tempprojectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempprojectphoto',
            name='temp_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_project_photos', to='users.tempproject'),
        ),
    ]
