# Generated by Django 4.0.5 on 2022-10-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answernotification',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answernotification',
            name='notified_user',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='helpfulnotification',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='helpfulnotification',
            name='notified_user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='question',
            name='forum_topic',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerNotification',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
        migrations.DeleteModel(
            name='HelpfulNotification',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
