# Generated by Django 4.0.5 on 2022-10-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='description',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
