# Generated by Django 4.0.5 on 2022-10-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumtopic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
