# Generated by Django 4.0.5 on 2022-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.CharField(default='1900-1901', max_length=10),
        ),
    ]
