# Generated by Django 4.0.5 on 2022-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_schoolyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
