# Generated by Django 4.0.5 on 2022-10-21 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopic',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
